name: Build Source Tarballs
description: Build Source Tarballs


inputs:
  sha:
    description: Commit hash
    default: ${{ github.sha }}
  name:
    description: Package name
    default: ${{ github.event.repository.name }}
  tag:
    description: Package version tag
    default: ${{ github.ref_name }}


runs:
  using: composite
  steps:
    - uses: ./.github/actions/make-version
      with:
        sha: ${{ inputs.sha }}
        dir: ${{ inputs.name }}-${{ inputs.tag }}
    - shell: bash
      run: |
        rm -Rf "./${NAME}/.git"
        tar -cf "./${NAME}.src.tar" "./${NAME}"
        gzip -9k "./${NAME}.src.tar"
        zstd -19k "./${NAME}.src.tar"
        zip -9r "./${NAME}.src.zip" "./${NAME}"
      env:
        NAME: ${{ inputs.name }}-${{ inputs.tag }}
