name: Create New Release
description: Create New Release


inputs:
  tag:
    description: Release tag
    default: ${{ github.ref_name }}


runs:
  using: composite
  steps:
    - shell: bash
      run: |
        gh release delete -R "${REPO}" "${TAG}" || true
        gh release create -R "${REPO}" --verify-tag "${TAG}"
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
        TAG: ${{ inputs.tag }}
