name: Bug Report
description: Report a bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: '# Bug Report'
  - type: textarea
    attributes:
      label: Description
      placeholder: Description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: How to reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      placeholder: What actually happens?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      placeholder: Logs
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Environment'
  - type: input
    attributes:
      label: Operating system
  - type: input
    attributes:
      label: Browser
  - type: input
    attributes:
      label: Software version
    validations:
      required: true
  - type: input
    attributes:
      label: Dependencies versions
  - type: textarea
    attributes:
      label: Other Information
      placeholder: Anything else to add?
