name: Documentation Issue
description: Report a documentation issue
labels:
  - docs
body:
  - type: markdown
    attributes:
      value: '# Documentation Issue'
  - type: textarea
    attributes:
      label: Description
      placeholder: |
        What is the issue?
        Missing information?  Something is unclear?  Found a typo?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggestions
      placeholder: Any suggestions how to fix the issue?
