name: Test
run-name: Test -- ${{ inputs.commit }}
permissions:
  contents: read


on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit to test
        type: string
        required: true


jobs:

  linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: ls -A .
      - name: Setup Job
        uses: szatanjl/template/.github/actions/setup@main
        with:
          commit: ${{ inputs.commit }}
      - name: After
        run: ls -A .

  windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Before
        shell: bash
        run: ls -A .
      - name: Setup Job
        uses: szatanjl/template/.github/actions/setup@main
        with:
          commit: ${{ inputs.commit }}
      - name: After
        shell: bash
        run: ls -A .

  macos:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Before
        run: ls -A .
      - name: Setup Job
        uses: szatanjl/template/.github/actions/setup@main
        with:
          commit: ${{ inputs.commit }}
      - name: After
        run: ls -A .

  checkout-dir:
    name: Test Changing Checkout Directory
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: ls -A .
      - name: Setup Job
        uses: szatanjl/template/.github/actions/setup@main
        with:
          commit: ${{ inputs.commit }}
          checkout: src
      - name: After
        run: ls -A . src

  empty-dir:
    name: Test Setup Without Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: ls -A .
      - name: Setup Job
        uses: szatanjl/template/.github/actions/setup@main
        with:
          commit: ${{ inputs.commit }}
          checkout:
      - name: After
        run: ls -A .
